[tool.ruff]
# Simple configuration for graduate project
select = ["E", "F", "W", "I"]  # Errors, pyflakes, warnings, imports
ignore = ["E501"]  # Line too long (Black handles this)
line-length = 88

[tool.black]
line-length = 88